In [58]:
import pandas as pd
import re
import ast
from sklearn.preprocessing import MultiLabelBinarizer

In [59]:
df = pd.read_csv('train.tsv',sep='\t')

In [60]:
def get_languages_list(item):
    item = ast.literal_eval(item)
    languages = [language_dict['iso_639_1'] for language_dict in item]
    return languages

In [61]:
df['spoken_languages'] = df['spoken_languages'].apply(lambda x:get_languages_list(x))

In [63]:
df['spoken_languages']

0       [en, fr]
1           [en]
2           [en]
3           [en]
4           [en]
          ...
5210        [fr]
5211        [en]
5212        [en]
5213        [en]
5214        [en]
Name: spoken_languages, Length: 5215, dtype: object

In [65]:
mlb = MultiLabelBinarizer()

res = pd.DataFrame(mlb.fit_transform(df['spoken_languages']),
                   columns=mlb.classes_,
                   index=df.index)

In [66]:
res['af']

,af,am,ar,ay,bg,bm,bn,bo,br,bs,...,to,tr,uk,ur,vi,xh,xx,yi,zh,zu
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5210,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5211,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5212,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5213,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5214,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0